(in-package :daft)

(define-actor bullet ((:visual "shuttle.png")
                      (speed 1))
  (move-forward 2)
  (let ((a (actors-in-range 10)))
    (when (touching-p a)
      (play-sound :bang)
      (die))))

(define-actor ship ((:visual "shuttle2.png")
                    (start-time (now))
                    (last-bullet-time (now)))
  (let ((time (+ (mod start-time 2pi-f)
                 (mod (now) 2pi-f))))
    (setf x (* (sin time) 200))
    (when (> (- (now) last-bullet-time) 1)
      (setf last-bullet-time (now))
      (spawn 'bullet (v! 0 0)))))
